// Массив всех 80 слов, переводов и категорий
const words = [
    { word: "Adverse effects", translation: "побочные эффекты, неблагоприятные реакции", category: "Медицина" },
    { word: "Amplified", translation: "усиленный, раздутый", category: "Общее" },
    { word: "Antimicrobial resistance", translation: "устойчивость к антибиотикам/лекарствам", category: "Медицина" },
    { word: "Burden", translation: "бремя, нагрузка, тяжесть", category: "Общее" },
    { word: "Campaigns", translation: "компании, программы, организованные действия", category: "Общее" },
    { word: "Chain of protection", translation: "цепь защиты (система коллективного иммунитета)", category: "Медицина" },
    { word: "Collective action", translation: "совместные действия", category: "Социология" },
    { word: "Collective foresight", translation: "коллективная дальновидность", category: "Социология" },
    { word: "Confidence", translation: "доверие", category: "Психология" },
    { word: "Continuous innovation", translation: "постоянное развитие, внедрение новшеств", category: "Технологии" },
    { word: "Cornerstone", translation: "краеугольный камень, основа, фундамент", category: "Общее" },
    { word: "Countering", translation: "противодействуя, борясь с", category: "Общее" },
    { word: "Decades", translation: "десятилетия", category: "Общее" },
    { word: "Disinformation", translation: "дезинформация (намеренная ложь)", category: "Социология" },
    { word: "Drive economies forward", translation: "двигают экономику вперёд", category: "Экономика" },
    { word: "Emerging diseases", translation: "новые, возникающие заболевания", category: "Медицина" },
    { word: "Emphasize", translation: "подчёркивают, делают акцент на", category: "Общее" },
    { word: "Enabling", translation: "позволяя, давая возможность", category: "Общее" },
    { word: "Engines of prosperity", translation: "двигатели процветания", category: "Экономика" },
    { word: "Enhancing", translation: "укрепляя, повышая, усиливая", category: "Общее" },
    { word: "Ensuring", translation: "гарантируя, обеспечивая", category: "Общее" },
    { word: "Epidemics", translation: "эпидемии, массовые вспышки болезней", category: "Медицина" },
    { word: "Equitable access", translation: "равный, справедливый доступ", category: "Социология" },
    { word: "Equity", translation: "справедливость, равноправие", category: "Социология" },
    { word: "Eradication", translation: "полное уничтожение, искоренение", category: "Медицина" },
    { word: "Evolving biological adversaries", translation: "развивающиеся биологические угрозы (вирусы, бактерии)", category: "Медицина" },
    { word: "Falters", translation: "даёт сбой, ослабевает, колеблется", category: "Общее" },
    { word: "Forging", translation: "создаёт, куёт, разрабатывает", category: "Общее" },
    { word: "Foster", translation: "способствуют, поощряют, создают", category: "Общее" },
    { word: "Foundation", translation: "фундамент, основа", category: "Общее" },
    { word: "Freed up resources", translation: "высвободили ресурсы (деньги, время)", category: "Экономика" },
    { word: "Global cooperation", translation: "глобальное сотрудничество", category: "Политика" },
    { word: "Global initiatives", translation: "глобальные инициативы", category: "Политика" },
    { word: "Hard-won", translation: "завоёванные тяжёлым трудом", category: "Общее" },
    { word: "Herd immunity", translation: "коллективный иммунитет", category: "Медицина" },
    { word: "Hinder", translation: "затруднять, мешать, снижать", category: "Общее" },
    { word: "Hinges on", translation: "зависит от", category: "Общее" },
    { word: "Hurdle", translation: "препятствие, барьер", category: "Общее" },
    { word: "Immunization efforts", translation: "усилия по вакцинации", category: "Медицина" },
    { word: "Infectious diseases", translation: "заразные болезни", category: "Медицина" },
    { word: "Infrastructure", translation: "инфраструктура (дороги, сети, коммуникации)", category: "Экономика" },
    { word: "Innovation", translation: "нововведения, инновации", category: "Технологии" },
    { word: "Invisible enemies", translation: "невидимые враги (микробы, вирусы)", category: "Медицина" },
    { word: "Jeopardizing", translation: "ставля под угрозу, подвергая опасности", category: "Общее" },
    { word: "Life expectancy", translation: "продолжительность жизни", category: "Медицина" },
    { word: "Long-term effects", translation: "долгосрочные последствия", category: "Общее" },
    { word: "Misinformation", translation: "дезинформация, ложная информация", category: "Социология" },
    { word: "Morbidity", translation: "заболеваемость", category: "Медицина" },
    { word: "Mortality", translation: "смертность", category: "Медицина" },
    { word: "Outbreaks", translation: "вспышки заболеваний", category: "Медицина" },
    { word: "Outcomes", translation: "результаты, последствия", category: "Общее" },
    { word: "Precision science", translation: "высокоточная наука", category: "Технологии" },
    { word: "Prevalence", translation: "распространённость", category: "Общее" },
    { word: "Persistence", translation: "настойчивость, упорство", category: "Психология" },
    { word: "Productive workforce", translation: "производительная рабочая сила", category: "Экономика" },
    { word: "Profound", translation: "глубокие, значительные", category: "Общее" },
    { word: "Public health", translation: "здоровье населения, общественное здравоохранение", category: "Медицина" },
    { word: "Rapid-response", translation: "быстрого реагирования", category: "Общее" },
    { word: "Redefined", translation: "переопределила, изменила, придала новый смысл", category: "Общее" },
    { word: "Redirect", translation: "перенаправить", category: "Общее" },
    { word: "Resilience", translation: "устойчивость, способность противостоять", category: "Общее" },
    { word: "Reveal", translation: "выявляют, обнаруживают", category: "Общее" },
    { word: "Revolutionized", translation: "коренным образом изменили", category: "Общее" },
    { word: "Ripple effect", translation: "эффект домино, цепная реакция", category: "Общее" },
    { word: "Ripples outward", translation: "расходится волнами, распространяется", category: "Общее" },
    { word: "Robust", translation: "надёжные, мощные, устойчивые", category: "Общее" },
    { word: "Shared immunity", translation: "коллективный иммунитет", category: "Медицина" },
    { word: "Shielding", translation: "защищая, прикрывая", category: "Общее" },
    { word: "Societal reinvention", translation: "изменение общества, переустройство жизни", category: "Социология" },
    { word: "Socioeconomic", translation: "социально-экономические", category: "Экономика" },
    { word: "Stability", translation: "стабильность, устойчивость", category: "Общее" },
    { word: "Surveillance systems", translation: "системы наблюдения, мониторинга", category: "Технологии" },
    { word: "Threatening", translation: "угрожая, ставя под угрозу", category: "Общее" },
    { word: "Trajectory of survival", translation: "путь выживания (будущее человечества)", category: "Общее" },
    { word: "Transparent", translation: "прозрачная, открытая, честная", category: "Общее" },
    { word: "Triumph", translation: "победа, большой успех", category: "Общее" },
    { word: "Trust", translation: "доверие", category: "Психология" },
    { word: "Unlocks progress", translation: "открывает возможности для развития", category: "Общее" },
    { word: "Vanquished", translation: "побеждённые, уничтоженные", category: "Общее" },
    { word: "Vulnerable populations", translation: "уязвимые группы населения", category: "Социология" },
    { word: "Addressing", translation: "решение (проблемы), преодоление", category: "Общее" },
    { word: "Challenges", translation: "трудности, проблемы", category: "Общее" },
    { word: "Associated with", translation: "связанные с", category: "Общее" },
    { word: "Effectiveness", translation: "эффективность, действенность", category: "Общее" },
    { word: "Offering hope", translation: "вселяя надежду", category: "Психология" }
];
